[package]
name = "macro_test"
version = "0.1.0"
authors = ["AlexeyKarasev <karasev.alexey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srml-support = { path = ".." }
