[package]
name = "macro_test"
version = "0.1.0"
authors = ["AlexeyKarasev <karasev.alexey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
rustc-hex = { version = "2.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
serde = { version = "1.0", optional = true }

authority-discovery-primitives = { package = "substrate-authority-discovery-primitives", path = "../../../core/authority-discovery/primitives", default-features = false }
babe-primitives = { package = "substrate-consensus-babe-primitives", path = "../../../core/consensus/babe/primitives", default-features = false }
client = { package = "substrate-client", path = "../../../core/client", default-features = false }
node-primitives = { path = "../../../node/primitives", default-features = false }
offchain-primitives = { package = "substrate-offchain-primitives", path = "../../../core/offchain/primitives", default-features = false }
primitives = { package = "substrate-primitives",  path = "../../../core/primitives", default-features = false }
rstd = { package = "sr-std", path = "../../../core/sr-std", default-features = false }
sr-primitives = { path = "../../../core/sr-primitives", default-features = false }
sr-staking-primitives = { path = "../../../core/sr-staking-primitives", default-features = false }
substrate-keyring = { path = "../../../core/keyring", optional = true }
substrate-session = { path = "../../../core/session", default-features = false }
version = { package = "sr-version", path = "../../../core/sr-version", default-features = false }

authority-discovery = { package = "srml-authority-discovery", path = "../../../srml/authority-discovery", default-features = false }
authorship = { package = "srml-authorship", path = "../../../srml/authorship", default-features = false }
babe = { package = "srml-babe", path = "../../../srml/babe", default-features = false }
balances = { package = "srml-balances", path = "../../../srml/balances", default-features = false }
collective = { package = "srml-collective", path = "../../../srml/collective", default-features = false }
contracts = { package = "srml-contracts", path = "../../../srml/contracts", default-features = false }
democracy = { package = "srml-democracy", path = "../../../srml/democracy", default-features = false }
elections = { package = "srml-elections", path = "../../../srml/elections", default-features = false }
executive = { package = "srml-executive", path = "../../../srml/executive", default-features = false }
finality-tracker = { package = "srml-finality-tracker", path = "../../../srml/finality-tracker", default-features = false }
grandpa = { package = "srml-grandpa", path = "../../../srml/grandpa", default-features = false }
im-online = { package = "srml-im-online", path = "../../../srml/im-online", default-features = false }
indices = { package = "srml-indices", path = "../../../srml/indices", default-features = false }
membership = { package = "srml-membership", path = "../../../srml/membership", default-features = false }
offences = { package = "srml-offences", path = "../../../srml/offences", default-features = false }
session = { package = "srml-session", path = "../../../srml/session", default-features = false, features = ["historical"] }
staking = { package = "srml-staking", path = "../../../srml/staking", default-features = false }
srml-staking-reward-curve = { path = "../../../srml/staking/reward-curve"}
sudo = { package = "srml-sudo", path = "../../../srml/sudo", default-features = false }
support = { package = "srml-support", path = "../../../srml/support", default-features = false }
system = { package = "srml-system", path = "../../../srml/system", default-features = false }
timestamp = { package = "srml-timestamp", path = "../../../srml/timestamp", default-features = false }
treasury = { package = "srml-treasury", path = "../../../srml/treasury", default-features = false }
